import { Controller, Get } from '@nestjs/common';

@Controller('notifications')
export class NotificationsController {
  @Get('/')
  async getNotifications() {
    return [
      `Fusce mollis dapibus felis sed tristique. In malesuada sapien libero, ac tincidunt urna malesuada et. Quisque blandit vel risus nec convallis. Nulla et justo blandit, dapibus metus in, scelerisque diam. Praesent quam lacus, pellentesque vitae turpis ut, posuere sollicitudin augue. Integer pulvinar consequat eros, volutpat mattis tellus facilisis at. Integer laoreet sapien et faucibus tempor. Etiam ornare ipsum id nisl euismod, eu pulvinar est euismod. Phasellus ante augue, posuere quis tortor a, ornare euismod libero. Aenean vulputate a lacus ac elementum. Donec at dui ut massa convallis feugiat. Mauris eget tempus leo. Sed convallis metus vitae diam scelerisque, sed semper neque vehicula. In a tellus tortor. In hac habitasse platea dictumst. In orci est, sagittis ac accumsan ac, mollis eget dolor.`,
      `Fusce mollis dapibus felis sed tristique. In malesuada sapien libero, ac tincidunt urna malesuada et. Quisque blandit vel risus nec convallis. Nulla et justo blandit, dapibus metus in, scelerisque diam. Praesent quam lacus, pellentesque vitae turpis ut, posuere sollicitudin augue. Integer pulvinar consequat eros, volutpat mattis tellus facilisis at. Integer laoreet sapien et faucibus tempor. Etiam ornare ipsum id nisl euismod, eu pulvinar est euismod. Phasellus ante augue, posuere quis tortor a, ornare euismod libero. Aenean vulputate a lacus ac elementum. Donec at dui ut massa convallis feugiat. Mauris eget tempus leo. Sed convallis metus vitae diam scelerisque, sed semper neque vehicula. In a tellus tortor. In hac habitasse platea dictumst. In orci est, sagittis ac accumsan ac, mollis eget dolor.`,
      `In malesuada sapien libero, ac tincidunt urna malesuada et. Praesent quam lacus, pellentesque vitae turpis ut, posuere sollicitudin augue. Integer pulvinar consequat eros, volutpat mattis tellus facilisis at. Integer laoreet sapien et faucibus tempor. Etiam ornare ipsum id nisl euismod, eu pulvinar est euismod. Phasellus ante augue, posuere quis tortor a, ornare euismod libero. Aenean vulputate a lacus ac elementum. Donec at dui ut massa convallis feugiat. Mauris eget tempus leo. Sed convallis metus vitae diam scelerisque, sed semper neque vehicula. In a tellus tortor. In hac habitasse platea dictumst. In orci est, sagittis ac accumsan ac, mollis eget dolor.`,
      `Fusce mollis dapibus felis sed tristique. In malesuada sapien libero, ac tincidunt urna malesuada et. Quisque blandit vel risus nec convallis. Nulla et justo blandit, dapibus metus in, scelerisque diam. Praesent quam lacus, pellentesque vitae turpis ut, posuere sollicitudin augue. Integer pulvinar consequat eros, volutpat mattis tellus facilisis at. Integer laoreet sapien et faucibus tempor. Etiam ornare ipsum id nisl euismod, eu pulvinar est euismod. Phasellus ante augue, posuere quis tortor a, ornare euismod libero. Aenean vulputate a lacus ac elementum. Donec at dui ut massa convallis feugiat. Mauris eget tempus leo. Sed convallis metus vitae diam scelerisque, sed semper neque vehicula. In a tellus tortor. In hac habitasse platea dictumst. In orci est, sagittis ac accumsan ac, mollis eget dolor.`,
      `Fusce mollis dapibus felis sed tristique. In malesuada sapien libero, ac tincidunt urna malesuada et. Quisque blandit vel risus nec convallis. Nulla et justo blandit, dapibus metus in, scelerisque diam. Praesent quam lacus, pellentesque vitae turpis ut, posuere sollicitudin augue. Integer pulvinar consequat eros, volutpat mattis tellus facilisis at. Integer laoreet sapien et faucibus tempor. Etiam ornare ipsum id nisl euismod, eu pulvinar est euismod. Phasellus ante augue, posuere quis tortor a, ornare euismod libero. Aenean vulputate a lacus ac elementum. Donec at dui ut massa convallis feugiat. Mauris eget tempus leo. Sed convallis metus vitae diam scelerisque, sed semper neque vehicula. In a tellus tortor. In hac habitasse platea dictumst. In orci est, sagittis ac accumsan ac, mollis eget dolor.`,
    ];
  }
}
